remote_theme: tomjoht/documentation-theme-jekyll

topnav_title: Vocal Art Project
# this appears on the top navigation bar next to the home button


company_name: Copyright 2022
# this appears in the footer


topnav: topnav
  scope:
    path: "/pages/wiki"
    type: "pages"
  values:
    layout: "page"
    comments: true
    search: true
    sidebar: home_sidebar
    topnav: topnav
